typography_spectrum: 0.2852736711502075
color:
  brandStrength: 0.29899624874815345
  lightness: 0.9758556184824556
  saturation: 0.5736724562011659
  rhythmicContrast: 0.5283592911437154
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
layout_spectrum: 0.021805089665576816
author:
  email: info@beyondeventsbali.com
  url: www.beyondeventsbali.com
  name: 'The Beyond Group Bali  '
logo: null
name: Beyond Events Bali
title: We make dreams come true!
